ES6-ify and fix lint
UKHomeOfficeForms/hof-form-controller pull request #9
Opened 2017-02-10 16:42 UTC by joefitter

* Removed underscore, replaced with lodash
* installed eslint-config-homeoffice
* fixed linting errors

2017-02-10 16:46 UTC, lennym commented
![](https://media.giphy.com/media/pXPOApWXuJaMw/giphy.gif)

2017-02-10 17:32 UTC, lennym requested changes

2017-02-10 17:32 UTC, lennym commented on package.json
> +    "snyk": "snyk auth $SNYK_TOKEN && snyk test",
This needs to be `$SNYK_AUTH` not `$SNYK_TOKEN` judging by the current travis settings.

<img width="569" alt="screen shot 2017-02-10 at 17 32 19" src="https://cloud.githubusercontent.com/assets/117398/22837060/ebea1c88-efb6-11e6-9cca-e79243d57e49.png">

2017-02-13 11:38 UTC, JoeChapman commented on lib/validation/index.js
> +    var args = [value];
if es6-ifying, why not use `let` here?

2017-02-13 11:40 UTC, JoeChapman commented on package.json
> +    "check-coverage": "istanbul check-coverage --statement 90 --branch 90 --function 90 --line 90",
why 90?

2017-02-13 11:41 UTC, JoeChapman commented on package.json
> +    "snyk": "snyk auth $SNYK_AUTH && snyk test",
oh cool so we set the env var `SNYK_AUTH`. Is it only set during CI?

2017-02-13 11:42 UTC, JoeChapman commented on package.json
>      "moment": "^2.9.0",
Perhaps use the latest; `2.17.1 `

2017-02-13 11:43 UTC, JoeChapman commented on package.json
>      "moment": "^2.9.0",
appreciate this is not an attempt to update all deps though

2017-02-13 11:45 UTC, joefitter commented on package.json
> +    "check-coverage": "istanbul check-coverage --statement 90 --branch 90 --function 90 --line 90",
why 98.31?

2017-02-13 11:45 UTC, joefitter commented on package.json
> +    "snyk": "snyk auth $SNYK_AUTH && snyk test",
yeah - in travis config using travis encrypt

2017-02-13 11:46 UTC, joefitter commented on package.json
>      "moment": "^2.9.0",
this will still get 2.17.1

2017-02-13 11:47 UTC, joefitter commented on lib/validation/index.js
> +    var args = [value];
missed one, updating!

2017-02-13 11:49 UTC, JoeChapman commented on package.json
> +    "check-coverage": "istanbul check-coverage --statement 90 --branch 90 --function 90 --line 90",
precisely

2017-02-13 11:49 UTC, JoeChapman commented on package.json
> +    "check-coverage": "istanbul check-coverage --statement 90 --branch 90 --function 90 --line 90",
0 or 100

2017-02-13 11:56 UTC, joefitter commented on package.json
> +    "check-coverage": "istanbul check-coverage --statement 90 --branch 90 --function 90 --line 90",
it was 98.31 as that's what hmpo set it to, as that was their current coverage, and they wanted to make sure it didn't drop when new code was added. Which is fair. _however_ adding all the code and tests from hof-base-controller results in test coverage dropping by like half a percent. And seeing as this isn't a PR to increase test coverage I set it to 90 to get the build to pass. I could just have removed the check, happy to do this if you prefer?

2017-02-13 11:57 UTC, JoeChapman commented on package.json
>      "moment": "^2.9.0",
uh, yep sorry.

2017-02-13 11:59 UTC, JoeChapman commented on package.json
> +    "check-coverage": "istanbul check-coverage --statement 90 --branch 90 --function 90 --line 90",
It doesn't hut to have it there. (AFAIK) I just thought it was an arbitrary choice.

2017-02-13 12:01 UTC, JoeChapman commented on package.json
> +    "snyk": "snyk auth $SNYK_AUTH && snyk test",
that was my next question (encryption) nice one.

2017-02-13 12:03 UTC, joefitter commented on package.json
> +    "check-coverage": "istanbul check-coverage --statement 90 --branch 90 --function 90 --line 90",
it is, kinda... more than 0, less than 100

2017-02-13 12:03 UTC, lennym approved these changes

2017-02-13 12:09 UTC, merged